#!/usr/bin/env python3
"""FastAPI server for the commons demo.

Three routes and nothing else: login, context refresh, and the dispatcher that
carries every other operation. Plugin loading, model generation and the admin
seed come from demo.py, so the smoke test and the server always run the same
application.

Run from this directory:  python fastapi-server.py
"""
import os

from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

import demo  # also puts the coframe package on sys.path  # noqa: E402
import coframe.server_utils as srv  # noqa: E402
from coframe.i18n import set_locale  # noqa: E402

# ── Application ─────────────────────────────────────────────────────────────

coframe_app, plugins = demo.setup()

import model  # type: ignore  # generated by demo.setup()  # noqa: E402

coframe_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
demo.seed(coframe_app, model)

command_processor = coframe_app.cp

SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key")
api_prefix = f"/{plugins.config.get('api', {}).get('prefix', 'coframe')}"
endpoint_prefix = plugins.config.get("api", {}).get("endpoint_prefix", "endpoint")

auth = srv.AuthMiddleware(plugins.config, SECRET_KEY)

app = FastAPI(
    title="Coframe commons demo",
    description="Reference app for the shared plugins",
    version=plugins.config.get("version", "0.0.0"),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def token_refresh(request: Request, call_next):
    """Hand a refreshed token back in X-New-Token whenever one was issued."""
    response = await call_next(request)
    if hasattr(request.state, "new_token"):
        response.headers["X-New-Token"] = request.state.new_token
    return response


async def current_user(request: Request) -> dict:
    """Validate the bearer token, refresh it when due, set the request locale."""
    token, error = auth.extract_token(request.headers.get("authorization"))
    if error:
        raise HTTPException(status_code=401, detail=error)

    payload, new_token, error = auth.decode_and_refresh(token)
    if error:
        raise HTTPException(status_code=401, detail=error)
    if new_token:
        request.state.new_token = new_token

    set_locale(payload.get("locale") or plugins.config.get("locale", "en"))
    return payload


# ── Routes ──────────────────────────────────────────────────────────────────


@app.get("/info")
def app_info():
    return srv.get_app_info(plugins.config, api_prefix)


@app.post(f"{api_prefix}/auth/login")
def login(data: dict):
    try:
        return auth.login(command_processor, data)
    except Exception as e:
        return {"status": "error", "message": str(e), "status_code": 500}


@app.post(f"{api_prefix}/auth/update_context")
def update_context(data: dict, user: dict = Depends(current_user)):
    return auth.update_context(user, data)


@app.post(f"{api_prefix}/{endpoint_prefix}/{{operation}}")
def dispatch(operation: str, data: dict, user: dict = Depends(current_user)):
    """Everything that is not authentication: db, query, get_page, get_menu…"""
    return srv.handle_generic_endpoint(command_processor, operation, data, context=user)


# A built client, when there is one — mounted last so the API routes win.
if os.path.isdir("static_client"):
    app.mount("/", StaticFiles(directory="static_client", html=True), name="client")


if __name__ == "__main__":
    import uvicorn

    port = plugins.config.get("api", {}).get("port", 8302)
    print(f"\n🚀 Coframe commons demo on port {port}")
    print(f"📖 OpenAPI docs: http://localhost:{port}/docs\n")
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
