#!/usr/bin/env python3
"""FastAPI server for the commons demo.

Four routes and nothing else: login, context refresh, the dispatcher that
carries every other operation, and info — registered by `srv.register_fastapi`
on the application itself, because this file *is* the application. Plugin
loading, model generation and the admin seed come from demo.py, so the smoke
test and the server always run the same application.

Run from this directory:  uv run server_fastapi.py
"""
import os

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

import demo
import coframe.server_utils as srv

# ── Application ─────────────────────────────────────────────────────────────

coframe_app, plugins = demo.setup()

import model  # type: ignore  # generated by demo.setup()  # noqa: E402

coframe_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
demo.seed(coframe_app, model)

# 32 bytes at least: below that PyJWT warns that the key is weak for
# HS256, and a warning nobody can act on is a warning people learn to skip.
SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key-not-for-service")

app = FastAPI(
    title="Coframe commons demo",
    description="Reference app for the shared plugins",
    version=plugins.config.get("version", "0.0.0"),
)

# ── Routes ──────────────────────────────────────────────────────────────────

srv.register_fastapi(app, coframe_app, plugins, SECRET_KEY)


# A built client, when there is one — mounted last so the API routes win.
if os.path.isdir("static"):
    app.mount("/", StaticFiles(directory="static", html=True), name="client")


if __name__ == "__main__":
    import uvicorn

    port = plugins.config.get("api", {}).get("port", 8302)
    print(f"\n🚀 Coframe commons demo on port {port}")
    print(f"📖 OpenAPI docs: http://localhost:{port}/docs\n")
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
